sudo: false
language: java
jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/money
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
after_success:
  - if [[ $TRAVIS_TAG =~ ^website.*$ ]] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk10" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk10" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
# secure keys for GITHUB_TOKEN
env:
  global:
  - secure: J2e5pXOU4H1XdnSxRl3zpC1L7Ka/TVG5qzMKzYW/S2u5PEqemMYaSJVYwsmMstBLHLMCSSwDaEkfVrxvaNkQL2wQ44yWXQo/s/UQCUlj80bF/2Vrp2hZu9nJoHW/UxtEFoQky+6O+AeGzrIO4glWK15uGE9p+aYZMcJjUW8a0TU=
