name: Build

on: 
  push:
    branches:
      - '*'
    tags:
      - 'v*'
      - 'website*'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '41 19 * * 2'

permissions:
  contents: read

jobs:
  build:
    permissions:
      security-events: write  # for github/codeql-action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'

    - name: Maven version
      run: |
        mkdir -p ./.mvn
        echo '-e -B -ntp -DtrimStackTrace=false' > ./.mvn/maven.config
        mvn --version
        mkdir -p target

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
    
    - name: Maven build
      run: |
        mvn install site

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
    
    - name: Website
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/website') || startsWith(github.ref, 'refs/tags/v'))
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GH }}
      run: |
        chmod +x ./.github/website.sh
        .github/website.sh
